
services:
  - type: web
    name: nasdaq-analysis
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: ALPHA_VANTAGE_API_KEY
        sync: false